### ISSUE TITLE
As a user, I want to be able to receive a meme template from a list of templates retrieved from an external API, so that I can create a meme.

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-server#12]
## Acceptance Criteria
- [x] sopra-fs23-group-13/meme-it-server#90
- [x] sopra-fs23-group-13/meme-it-client#14
- [ ] sopra-fs23-group-13/meme-it-server#52
- [ ] sopra-fs23-group-13/meme-it-server#106

## Tests
- [ ] Select a meme template and verify that it is added to the player's meme creation screen.
- [ ] Verify that the image of the selected template is displayed to the player.
- [ ] Verify that new templates added to the API are included in the list of available templates.
- [ ] The timer should not reset if the new meme template.
