### ISSUE TITLE
As a user I want to be able to pick a name so I can identify myself in-game

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-server#3]
## Acceptance Criteria
- [x] sopra-fs23-group-13/meme-it-client#41
- [ ] sopra-fs23-group-13/meme-it-client#40
- [ ] sopra-fs23-group-13/meme-it-client#39
- [x] sopra-fs23-group-13/meme-it-client#60

## Tests
- [ ] Name should stay the same as long as player doesn't quit the session.
- [ ] Name should be reset and player should be required to set a name again after a certain amount of absence from the website.
