### ISSUE TITLE
As a user, I want to be able to create my own lobby and customize the game settings to my preferred game options.

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-server#73]
## Acceptance Criteria
- [x] sopra-fs23-group-13/meme-it-server#65
- [x] sopra-fs23-group-13/meme-it-client#6
- [x] sopra-fs23-group-13/meme-it-client#7
- [ ] sopra-fs23-group-13/meme-it-server#77

## Tests

- [ ] Lobby is disbanded and all players are kicked if the lobby creator quits their session.
- [ ] Customization of game rules should only be allowed within certain minimum and maximum values.
- [ ] Players that are kicked should be redirected to the main page and be notified with an alert.
